# Generated by Django 5.0.1 on 2025-12-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveIntegerField(help_text='Year the achievement was earned')),
                ('category', models.CharField(choices=[('trophy', 'Trophy'), ('championship', 'Championship'), ('award', 'Award'), ('recognition', 'Recognition')], default='trophy', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Image of trophy/award (recommended: 400x400)', upload_to='achievements/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['display_order', '-year', '-created_at'],
            },
        ),
    ]
