# Generated by Django 5.0.1 on 2025-12-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('issuing_body', models.CharField(help_text='Organization that issued the accreditation (e.g., FIFA, UEFA, AIFF)', max_length=200)),
                ('accreditation_type', models.CharField(choices=[('certification', 'Certification'), ('affiliation', 'Affiliation'), ('partnership', 'Partnership'), ('membership', 'Membership')], default='certification', max_length=20)),
                ('logo', models.ImageField(help_text='Logo of the accrediting body (recommended: 200x200)', upload_to='accreditations/')),
                ('website_url', models.URLField(blank=True, help_text='Link to accrediting organization')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Accreditation',
                'verbose_name_plural': 'Accreditations',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
