# Generated by Django 5.0.1 on 2025-12-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Star rating (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='accreditation',
            name='rating_label',
            field=models.CharField(blank=True, help_text="Rating label (e.g., '4 Star Rating', 'Elite Academy')", max_length=100),
        ),
    ]
