# Generated by Django 5.0.1 on 2025-12-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='description',
            field=models.TextField(blank=True, help_text='Additional description text'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the image (for accessibility & SEO)', max_length=200),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Type of media for this slide', max_length=10),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 characters)', max_length=160),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video',
            field=models.FileField(blank=True, help_text='Upload video file (MP4 recommended)', null=True, upload_to='hero/videos/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Poster/thumbnail image shown before video plays', null=True, upload_to='hero/posters/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo embed URL)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the slide (recommended: 1920x1080)', null=True, upload_to='hero/'),
        ),
    ]
