# Generated by Django 5.0.1 on 2025-12-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AIFA Sports Academy', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('logo_white', models.ImageField(blank=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/')),
                ('email', models.EmailField(default='info@aifasports.com', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True, help_text='Google Maps iframe embed code')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, upload_to='site/')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('footer_about', models.TextField(blank=True, help_text='Short about text for footer')),
                ('copyright_text', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
