# Generated by Django 5.0.1 on 2025-12-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(default='WHERE PASSION MEETS EXCELLENCE', help_text='Main story section title', max_length=200)),
                ('story_content', models.TextField(blank=True, help_text='Rich text content for the story/mission section (HTML supported)')),
                ('story_image', models.ImageField(blank=True, help_text='Image for the story section', upload_to='pages/about/')),
                ('founding_year', models.PositiveIntegerField(default=2014, help_text='Year the academy was founded')),
                ('core_values', models.JSONField(blank=True, default=list, help_text='List of core values. Format: [{"icon": "star", "title": "Excellence", "description": "..."}]')),
                ('statistics', models.JSONField(blank=True, default=dict, help_text='Statistics. Format: {"students_trained": 5000, "trophies_won": 50, "district_players": 100, "years_excellence": 10}')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge_text', models.CharField(default='#1 Rated Football Academy', help_text='Text shown in the hero badge', max_length=100)),
                ('marquee_items', models.JSONField(blank=True, default=list, help_text='List of marquee text items. Format: ["Elite Training", "Professional Coaches"]')),
                ('about_section_tag', models.CharField(default='About Our Academy', help_text='Tag text above the about section title', max_length=50)),
                ('about_section_title', models.CharField(default='WHERE <span class="text-accent">Passion</span><br>MEETS EXCELLENCE', help_text='About section title (HTML supported for styling)', max_length=200)),
                ('about_section_text', models.TextField(blank=True, help_text='Preview text for about section on homepage')),
                ('about_section_features', models.JSONField(blank=True, default=list, help_text='Features list. Format: [{"icon": "clock", "text": "UEFA Licensed Coaches"}]')),
                ('cta_title', models.CharField(default='READY TO BEGIN?', help_text='CTA section title', max_length=100)),
                ('cta_text', models.TextField(default='Book a free trial session today and experience world-class football training firsthand.', help_text='CTA section description')),
                ('cta_button_text', models.CharField(default='Book Free Trial', help_text='Primary CTA button text', max_length=50)),
                ('cta_button_link', models.CharField(default='/contact/', help_text='Primary CTA button link', max_length=200)),
                ('show_statistics', models.BooleanField(default=True, help_text='Show the statistics section on homepage')),
                ('statistics_background_text', models.CharField(default='CHAMPIONS', help_text='Large background text in statistics section', max_length=50)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('programs', 'Programs'), ('coaches', 'Coaches'), ('events', 'Events'), ('news', 'News'), ('gallery', 'Gallery')], help_text='Select the page this setting applies to', max_length=20, unique=True)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero background image (recommended: 1920x1080)', upload_to='pages/hero/')),
                ('hero_title', models.CharField(blank=True, help_text='Main hero title (supports HTML tags for styling)', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Subtitle text below the main title', max_length=300)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 characters)', max_length=70)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description (max 160 characters)', max_length=160)),
            ],
            options={
                'verbose_name': 'Page Setting',
                'verbose_name_plural': 'Page Settings',
                'ordering': ['page_type'],
            },
        ),
    ]
