# Generated by Django 5.0.1 on 2025-12-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_boardmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='mission_content',
            field=models.TextField(blank=True, help_text='Mission statement content (HTML supported)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='mission_title',
            field=models.CharField(default='Our Mission', help_text='Mission section title', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='vision_content',
            field=models.TextField(blank=True, help_text='Vision statement content (HTML supported)'),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='vision_title',
            field=models.CharField(default='Our Vision', help_text='Vision section title', max_length=200),
        ),
    ]
