# Generated by Django 5.0.1 on 2025-12-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutpagecontent_mission_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('charity', 'Charity Event'), ('outreach', 'Community Outreach'), ('coaching', 'Free Coaching Camp'), ('donation', 'Donation Drive'), ('awareness', 'Awareness Program'), ('other', 'Other')], default='outreach', max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, help_text='Brief summary for cards', max_length=300)),
                ('image', models.ImageField(upload_to='community/')),
                ('date', models.DateField(help_text='Date of the activity')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('beneficiaries', models.CharField(blank=True, help_text="e.g., '500 underprivileged children'", max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_on_website', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Community Activity',
                'verbose_name_plural': 'Community Activities',
                'ordering': ['-date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='COMMUNITY OUTREACH', help_text='Hero section title', max_length=200)),
                ('hero_subtitle', models.CharField(default='Making a Difference Beyond the Field', help_text='Hero section subtitle', max_length=300)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero background image', upload_to='pages/community/')),
                ('intro_title', models.CharField(default='Giving Back to Our Community', help_text='Introduction section title', max_length=200)),
                ('intro_content', models.TextField(blank=True, help_text='Introduction content (HTML supported)')),
                ('stats_volunteers', models.PositiveIntegerField(default=50, help_text='Number of volunteers')),
                ('stats_events', models.PositiveIntegerField(default=25, help_text='Number of events conducted')),
                ('stats_beneficiaries', models.PositiveIntegerField(default=2000, help_text='Number of beneficiaries')),
                ('stats_hours', models.PositiveIntegerField(default=500, help_text='Volunteer hours')),
            ],
            options={
                'verbose_name': 'Community Page Content',
                'verbose_name_plural': 'Community Page Content',
            },
        ),
    ]
