# Generated by Django 5.0.1 on 2025-12-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_communityactivity_communitypagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='aifl_logo',
            field=models.ImageField(blank=True, help_text='All India Football League logo for navbar', upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kfa_logo',
            field=models.ImageField(blank=True, help_text='Kerala Football Association logo for navbar', upload_to='site/'),
        ),
    ]
