# Generated by Django 5.0.1 on 2025-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_federation_logos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='aifl_logo_alt',
            field=models.CharField(blank=True, default='AIFL', help_text='Alt text for AIFL logo', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='kfa_logo_alt',
            field=models.CharField(blank=True, default='KFA', help_text='Alt text for KFA logo', max_length=200),
        ),
    ]
