# Generated by Django 5.0.1 on 2025-12-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='programs/')),
                ('age_group', models.CharField(help_text="e.g., '6-12 years'", max_length=50)),
                ('duration', models.CharField(help_text="e.g., '3 months'", max_length=50)),
                ('sessions_per_week', models.PositiveIntegerField(default=3)),
                ('session_duration', models.CharField(default='90 minutes', max_length=50)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_period', models.CharField(default='monthly', max_length=20)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features')),
                ('status', models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.CharField(help_text="e.g., 'Mon, Wed, Fri - 4:00 PM'", max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('max_capacity', models.PositiveIntegerField(default=20)),
                ('current_strength', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='active', max_length=20)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='coaches.coach')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='programs.program')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-start_date'],
            },
        ),
    ]
