# Generated by Django 5.0.1 on 2025-12-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 70 chars)', max_length=70),
        ),
    ]
