# Generated by Django 5.0.1 on 2025-12-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_add_meta_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('youtube_shorts', 'YouTube Shorts'), ('instagram', 'Instagram Reels'), ('facebook', 'Facebook'), ('tiktok', 'TikTok')], default='youtube', max_length=20)),
                ('video_url', models.URLField(help_text='Paste the video URL (YouTube, Instagram, Facebook, or TikTok)')),
                ('video_id', models.CharField(blank=True, help_text='Auto-extracted from URL', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, help_text='Custom thumbnail (optional)', upload_to='gallery/video_thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Video',
                'verbose_name_plural': 'Gallery Videos',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
